name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore .\jcGAI\jcGAI.WebAPI\jcGAI.WebAPI.csproj
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/jcGAI/jcGAI.WebAPI/appsettings.json'
      env:
        OAuth.ClientId: ${{ secrets.OATH_CLIENTID }}
        OAuth.Secret: ${{ secrets.OATH_SECRET }}
    - name: Build
      run: dotnet build --no-restore .\jcGAI\jcGAI.WebAPI\jcGAI.WebAPI.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal .\jcGAI\jcGAI.WebAPI\jcGAI.WebAPI.csproj
